# This is a basic workflow to help you get started with Actions

name: ingestion3 remap

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  #   sh ingest-emr.sh


#  i3-remap ()
#  {
#  SBT_OPTS=-Xmx12g sbt "runMain dpla.ingestion3.entries.ingest.IngestRemap
#  --output s3://dpla-master-dataset/
#  --conf ./ingestion3/conf/i3.conf
#  --name nara
#  --input s3://dpla-master-dataset/
#  --sparkMaster local[*]"
#  }

  workflow_dispatch:
    inputs:
      input:
        description: 'Harvest input'
        required: true
        default: 's3a://dpla-master-dataset/'
      output:
        description: 'Ingest output'
        required: true
        default: 's3a://dpla-master-dataset/'
      name:
        description: 'Provider name'
        required: true
      ec2_size:
        description: 'EC2 size'
        required: true
        default: 'm6g.2xlarge'
jobs:
  # This workflow contains a single job called "ingest"
  ingest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Run ingest-emr.sh file
        run: |
          chmod +x ./ingest-emr.sh
          ./ingest-emr.sh ${{ github.event.inputs.output }} ${{ github.event.inputs.name }} ${{ github.event.inputs.input }} ${{ github.event.inputs.ec2_size }}
        shell: bash